PAST50 = 0.47
PAST80 = 0.23

BASIC_ARCHER = 60
RANGE_ARCHER = 80
SPECIAL_ARCHER = 120
GRIP_ARCHER = 100
CELLDESTRUCTION_ARCHER = 4
ENERGY_ARCHER = 130
ARMOR_ARCHER = 130
ATTACKSPEED_ARCHER = 98
MOVEMENTSPEED_ARCHER = 7
CELLPOINTS_ARCHER = 2000

BASIC_PER_STATPOINT_ARCHER = 1
RANGE_PER_STATPOINT_ARCHER = 1
SPECIAL_PER_STATPOINT_ARCHER = 1
GRIP_PER_STATPOINT_ARCHER = 1
CELLDEST_PER_STATPOINT_ARCHER = 1
ENERGY_PER_STATPOINT_ARCHER = 2
ARMOR_PER_STATPOINT_ARCHER = 2
ATTACKSPED_PER_STATPOINT_ARCHER = 0.14
MOVSPEED_PER_STATPOINT_ARCHER = 0.024
CELLPOINTS_PER_STATPOINT_ARCHER = 180

