PAST50 = 0.47
PAST80 = 0.23

BASIC_BLACKSMITH = 80
RANGE_BLACKSMITH = 120
SPECIAL_BLACKSMITH = 125
GRIP_BLACKSMITH = 120
CELLDESTRUCTION_BLACKSMITH = 18
ENERGY_BLACKSMITH = 180
ARMOR_BLACKSMITH = 180
ATTACKSPEED_BLACKSMITH = 98
MOVEMENTSPEED_BLACKSMITH = 7.2
CELLPOINTS_BLACKSMITH = 3000

BASIC_PER_STATPOINT_BLACKSMITH = 1
RANGE_PER_STATPOINT_BLACKSMITH = 1
SPECIAL_PER_STATPOINT_BLACKSMITH = 1
GRIP_PER_STATPOINT_BLACKSMITH = 1
CELLDEST_PER_STATPOINT_BLACKSMITH = 1
ENERGY_PER_STATPOINT_BLACKSMITH = 2
ARMOR_PER_STATPOINT_BLACKSMITH = 2
ATTACKSPED_PER_STATPOINT_BLACKSMITH = 0.18
MOVSPEED_PER_STATPOINT_BLACKSMITH = 0.024
CELLPOINTS_PER_STATPOINT_BLACKSMITH = 200

