PAST50 = 0.47
PAST80 = 0.23

BASIC_DUALIST = 90
RANGE_DUALIST = 120
SPECIAL_DUALIST = 120
GRIP_DUALIST = 100
CELLDESTRUCTION_DUALIST = 15
ENERGY_DUALIST = 170
ARMOR_DUALIST = 170
ATTACKSPEED_DUALIST = 98
MOVEMENTSPEED_DUALIST = 7.5
CELLPOINTS_DUALIST = 2600

BASIC_PER_STATPOINT_DUALIST = 1
RANGE_PER_STATPOINT_DUALIST = 1
SPECIAL_PER_STATPOINT_DUALIST = 1
GRIP_PER_STATPOINT_DUALIST = 1
CELLDEST_PER_STATPOINT_DUALIST = 1
ENERGY_PER_STATPOINT_DUALIST = 2
ARMOR_PER_STATPOINT_DUALIST = 2
ATTACKSPED_PER_STATPOINT_DUALIST = 0.18
MOVSPEED_PER_STATPOINT_DUALIST = 0.026
CELLPOINTS_PER_STATPOINT_DUALIST = 200

