PAST50 = 0.47
PAST80 = 0.23

BASIC_MAGE = 60
RANGE_MAGE = 90
SPECIAL_MAGE = 100
GRIP_MAGE = 100
CELLDESTRUCTION_MAGE = 17
ENERGY_MAGE = 125
ARMOR_MAGE = 125
ATTACKSPEED_MAGE = 98
MOVEMENTSPEED_MAGE = 6.5
CELLPOINTS_MAGE = 3500

BASIC_PER_STATPOINT_MAGE = 1
RANGE_PER_STATPOINT_MAGE = 1
SPECIAL_PER_STATPOINT_MAGE = 1
GRIP_PER_STATPOINT_MAGE = 1
CELLDEST_PER_STATPOINT_MAGE = 1
ENERGY_PER_STATPOINT_MAGE = 2
ARMOR_PER_STATPOINT_MAGE = 2
ATTACKSPED_PER_STATPOINT_MAGE = 0.16
MOVSPEED_PER_STATPOINT_MAGE = 0.022
CELLPOINTS_PER_STATPOINT_MAGE = 240

