PAST50 = 0.47
PAST80 = 0.23

BASIC_NINJA = 70
RANGE_NINJA = 90
SPECIAL_NINJA = 100
GRIP_NINJA = 100
CELLDESTRUCTION_NINJA = 0
ENERGY_NINJA = 130
ARMOR_NINJA = 120
ATTACKSPEED_NINJA = 98
MOVEMENTSPEED_NINJA = 7.6
CELLPOINTS_NINJA = 1600

BASIC_PER_STATPOINT_NINJA = 1
RANGE_PER_STATPOINT_NINJA = 1
SPECIAL_PER_STATPOINT_NINJA = 1
GRIP_PER_STATPOINT_NINJA = 1
CELLDEST_PER_STATPOINT_NINJA = 1
ENERGY_PER_STATPOINT_NINJA = 2
ARMOR_PER_STATPOINT_NINJA = 2
ATTACKSPED_PER_STATPOINT_NINJA = 0.18
MOVSPEED_PER_STATPOINT_NINJA = 0.027
CELLPOINTS_PER_STATPOINT_NINJA = 120

