PAST50 = 0.47
PAST80 = 0.23

BASIC_SWORDMAN = 90
RANGE_SWORDMAN = 100
SPECIAL_SWORDMAN = 110
GRIP_SWORDMAN = 100
CELLDESTRUCTION_SWORDMAN = 15
ENERGY_SWORDMAN = 150
ARMOR_SWORDMAN = 150
ATTACKSPEED_SWORDMAN = 98
MOVEMENTSPEED_SWORDMAN = 7.5
CELLPOINTS_SWORDMAN = 2500

BASIC_PER_STATPOINT_SWORDMAN = 1
RANGE_PER_STATPOINT_SWORDMAN = 1
SPECIAL_PER_STATPOINT_SWORDMAN = 1
GRIP_PER_STATPOINT_SWORDMAN = 1
CELLDEST_PER_STATPOINT_SWORDMAN = 1
ENERGY_PER_STATPOINT_SWORDMAN = 2
ARMOR_PER_STATPOINT_SWORDMAN = 2
ATTACKSPED_PER_STATPOINT_SWORDMAN = 0.18
MOVSPEED_PER_STATPOINT_SWORDMAN = 0.026
CELLPOINTS_PER_STATPOINT_SWORDMAN = 200

